// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PhraseToMethod
{
    internal sealed partial class Vsix
    {
        public const string Id = "PhraseToMethod.c2db141d-95f0-4cec-8f0a-2b5d2a88580c";
        public const string Name = "PhraseToMethod";
        public const string Description = @"Convert a phrase to a method name in  pascal caseConvert a phrase to a method name in  pascal case";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "HP Inc.";
        public const string Tags = "";
    }
}
