// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PhraseToMethod
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PhraseToMethodString = "d2cc7f26-42fb-4c8d-858f-05f3fc3599d5";
        public static Guid PhraseToMethod = new Guid(PhraseToMethodString);

        public const string guidVSPackageCommandCodeWindowContextMenuCmdSetString = "bea4976d-811a-4dd0-9745-0bed7a658b5d";
        public static Guid guidVSPackageCommandCodeWindowContextMenuCmdSet = new Guid(guidVSPackageCommandCodeWindowContextMenuCmdSetString);

        public const string guidImagesString = "a156b47b-df48-4124-a918-ae1cd9492fcb";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyGroupForCommands = 0x1020;
        public const int MyGroupForSubmenu = 0x1021;
        public const int MySubmenu = 0x0100;
        public const int Command1Id = 0x0101;
        public const int Command2Id = 0x0102;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
    }
}